# Generated by Django 4.1.7 on 2023-05-10 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='topic',
        ),
        migrations.AddField(
            model_name='homework',
            name='topic',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='course.topic', verbose_name='Тема'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Курс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.topic', verbose_name='Тема'),
        ),
    ]
