# Generated by Django 4.1.7 on 2023-05-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_topic_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Оценка'),
        ),
    ]
