# Generated by Django 4.1.7 on 2023-06-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Курс'),
        ),
    ]
