# Generated by Django 4.1.7 on 2023-06-24 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_grade_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.topic', verbose_name='Тема'),
        ),
    ]
